// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rernunefhizrdwzafmuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlcm51bmVmaGl6cmR3emFmbXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NDYxMzEsImV4cCI6MjA2NzUyMjEzMX0.zze0d_4O8yJK_Q1_p4kS-ShQ3oPl_JSXn54kGUKmrmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});